apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: monitoring-kube-prometheus-prometheus
  namespace: monitoring
spec:
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
