# apiVersion: v1
# kind: Service
# metadata:
#   name: devops-service
# spec:
#   selector:
#     app: devops-app
#   ports:
#     - port: 80
#       targetPort: 5000
#   type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: devops-service
  labels:
    app: devops-app
spec:
  type: LoadBalancer
  selector:
    app: devops-app
  ports:
    - name: http
      port: 80
      targetPort: 5000

